package ru.per.jmseedmap.core;

import java.util.Optional;
import java.util.Random;
import net.minecraft.ChatFormatting;
import net.minecraft.client.Minecraft;
import net.minecraft.client.multiplayer.ClientLevel;
import net.minecraft.client.player.LocalPlayer;
import net.minecraft.core.QuartPos;
import net.minecraft.network.chat.Component;
import net.minecraft.resources.ResourceKey;
import net.minecraft.world.level.biome.Biome;
import net.minecraft.world.level.chunk.LevelChunk;
import net.minecraft.world.level.chunk.status.ChunkStatus;
import ru.per.jmseedmap.gen.GenContext;

/**
 * Verifies the seed against reality: the server sends real biomes with every chunk, so comparing them with
 * the biomes the seed predicts tells whether the seed, world type and version are right, long before
 * anyone walks to a wrong structure. Only biomes are compared, nothing is sent anywhere.
 */
public final class SeedCheck {
	public enum Verdict { UNKNOWN, OK, SUSPECT, WRONG }

	private static final int WINDOW = 240;
	private static final int MIN_SAMPLES = 48;
	private static final int SAMPLES_PER_RUN = 16;

	private final boolean[] window = new boolean[WINDOW];
	private final Random random = new Random();
	private int size;
	private int next;
	private int matches;
	private String contextId = "";
	private Verdict verdict = Verdict.UNKNOWN;
	private Verdict announced = Verdict.UNKNOWN;

	public Verdict verdict() {
		return verdict;
	}

	/** Share of matching samples in percent, or -1 before there is enough data. */
	public int percent() {
		return size < MIN_SAMPLES ? -1 : Math.round(matches * 100f / size);
	}

	public int samples() {
		return size;
	}

	/** Every ~5 seconds on the render thread. */
	void tick(Minecraft mc, StructureIndex index) {
		ClientLevel level = mc.level;
		LocalPlayer player = mc.player;
		if (level == null || player == null) {
			return;
		}
		GenContext ctx = index.context(level.dimension());
		if (ctx == null) {
			return;
		}
		if (!ctx.id().equals(contextId)) {
			reset(ctx.id());
		}
		int radius = Math.max(2, mc.options.getEffectiveRenderDistance() - 1);
		int pcx = player.chunkPosition().x();
		int pcz = player.chunkPosition().z();
		int minQuartY = QuartPos.fromBlock(level.getMinY());
		int quartHeight = QuartPos.fromBlock(level.getHeight());
		for (int i = 0; i < SAMPLES_PER_RUN; i++) {
			int cx = pcx + random.nextInt(radius * 2 + 1) - radius;
			int cz = pcz + random.nextInt(radius * 2 + 1) - radius;
			LevelChunk chunk = level.getChunkSource().getChunk(cx, cz, ChunkStatus.FULL, false);
			if (chunk == null || chunk.isEmpty()) {
				continue;
			}
			int qx = QuartPos.fromSection(cx) + random.nextInt(4);
			int qz = QuartPos.fromSection(cz) + random.nextInt(4);
			int qy = minQuartY + random.nextInt(quartHeight);
			Optional<ResourceKey<Biome>> actual = chunk.getNoiseBiome(qx, qy, qz).unwrapKey();
			Optional<ResourceKey<Biome>> predicted = ctx.generator().getBiomeSource()
				.getNoiseBiome(qx, qy, qz, ctx.randomState().sampler()).unwrapKey();
			if (actual.isEmpty() || predicted.isEmpty()) {
				continue;
			}
			add(actual.get().identifier().equals(predicted.get().identifier()));
		}
		update(mc);
	}

	private void add(boolean match) {
		if (size == WINDOW) {
			if (window[next]) {
				matches--;
			}
		} else {
			size++;
		}
		window[next] = match;
		if (match) {
			matches++;
		}
		next = (next + 1) % WINDOW;
	}

	private void update(Minecraft mc) {
		int percent = percent();
		if (percent < 0) {
			verdict = Verdict.UNKNOWN;
			return;
		}
		// Not 100%: chunks generated by an older game version keep their old biomes.
		verdict = percent >= 85 ? Verdict.OK : percent >= 40 ? Verdict.SUSPECT : Verdict.WRONG;
		if (verdict == announced || mc.player == null) {
			return;
		}
		// In singleplayer the seed comes from the world itself, so only bad news is worth a message.
		boolean singleplayer = mc.getSingleplayerServer() != null;
		if (verdict != Verdict.OK || !singleplayer) {
			ChatFormatting color = switch (verdict) {
				case OK -> ChatFormatting.GREEN;
				case SUSPECT -> ChatFormatting.YELLOW;
				default -> ChatFormatting.RED;
			};
			mc.player.sendSystemMessage(Component.translatable("jm_seedmap.check." + verdict.name().toLowerCase(java.util.Locale.ROOT), percent)
				.withStyle(color));
		}
		announced = verdict;
	}

	void reset(String id) {
		contextId = id;
		size = 0;
		next = 0;
		matches = 0;
		verdict = Verdict.UNKNOWN;
		announced = Verdict.UNKNOWN;
	}

	public Component describe() {
		int percent = percent();
		if (percent < 0) {
			return Component.translatable("jm_seedmap.check.status_unknown", size, MIN_SAMPLES);
		}
		return Component.translatable("jm_seedmap.check.status_" + verdict.name().toLowerCase(java.util.Locale.ROOT), percent, size);
	}
}
